# Generated by Django 5.1.4 on 2024-12-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('alt_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('alt_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('local', models.BooleanField(default=True)),
                ('host_small', models.BooleanField(default=False)),
                ('host_large', models.BooleanField(default=False)),
                ('host_children', models.BooleanField(default=False)),
                ('host_pets', models.BooleanField(default=False)),
                ('host_disable', models.BooleanField(default=False)),
                ('host_smoke', models.BooleanField(default=False)),
                ('host_mobile_accomodation', models.BooleanField(default=False)),
                ('host_long_term', models.BooleanField(default=False)),
                ('host_religious_kitchen', models.BooleanField(default=False)),
                ('host_comment', models.TextField(blank=True, null=True)),
                ('transport_station', models.BooleanField(default=False)),
                ('transport_local', models.BooleanField(default=False)),
                ('transport_pay_for_ride', models.BooleanField(default=False)),
                ('transport_pay_for_public', models.BooleanField(default=False)),
                ('transport_advice_for_public', models.BooleanField(default=False)),
                ('transport_loan_bike', models.BooleanField(default=False)),
                ('transport_loan_car', models.BooleanField(default=False)),
                ('transport_moving_vehicle', models.BooleanField(default=False)),
                ('transport_comment', models.TextField(blank=True, null=True)),
                ('donation_groceries', models.BooleanField(default=False)),
                ('donation_hygiene', models.BooleanField(default=False)),
                ('donation_household', models.BooleanField(default=False)),
                ('donation_baby_item', models.BooleanField(default=False)),
                ('donation_gift_card', models.BooleanField(default=False)),
                ('donation_winter_items', models.BooleanField(default=False)),
                ('donation_affirming_clothes', models.BooleanField(default=False)),
                ('donation_custom', models.TextField(blank=True, null=True)),
                ('donation_comment', models.TextField(blank=True, null=True)),
                ('settle_orient_to_city', models.BooleanField(default=False)),
                ('settle_orient_to_local_community', models.BooleanField(default=False)),
                ('settle_find_healthcare', models.BooleanField(default=False)),
                ('settle_parental_support', models.BooleanField(default=False)),
                ('settle_childcare', models.BooleanField(default=False)),
                ('settle_foster_pet', models.BooleanField(default=False)),
                ('settle_disability_connections', models.BooleanField(default=False)),
                ('settle_religious_connections', models.BooleanField(default=False)),
                ('settle_language_translation', models.BooleanField(default=False)),
                ('settle_custom', models.TextField(blank=True, null=True)),
                ('settle_comment', models.TextField(blank=True, null=True)),
                ('volunteering_administrative', models.BooleanField(default=False)),
                ('volunteering_data_entry', models.BooleanField(default=False)),
                ('volunteering_organizer', models.BooleanField(default=False)),
                ('volunteering_money_donation', models.BooleanField(default=False)),
                ('volunteering_custom', models.TextField(blank=True, null=True)),
                ('additional_professional', models.TextField(blank=True, null=True)),
                ('additional_employment', models.TextField(blank=True, null=True)),
                ('additional_custom', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
